# wrangler.toml — minimal static-site config
name = 'driveincanada'
account_id = "a62f6e85d86cbf0e919fd15b5869ab46"
compatibility_date = "2025-08-10"

# Serve static assets straight from the repo root (where index.html lives)
assets = "."

# Deploy to your workers.dev subdomain unless you add routes below
workers_dev = true

# If you have a Cloudflare-managed domain, uncomment and set these:
# routes = [
#   { pattern = "driveincanada.ca/*", zone_name = "driveincanada.ca" }
# ]
