name = "driveincanada"
account_id = "a62f6e85d86cbf0e919fd15b5869ab46"
compatibility_date = "2025-08-10"
workers_dev = true

[assets]
# serve files from the repo root (where index.html lives)
directory = "."
